### ISSUE TITLE
opencv-python versions load on every start up of webui

### ISSUE THREAD

**Issue by tmprabubiz** [s0md3v/sd-webui-roop#244]
Python 3.10.6 (tags/v3.10.6:9c7b4bd, Aug  1 2022, 21:53:49) [MSC v.1932 64 bit (AMD64)]
Version: v1.6.0
Commit hash: 5ef669de080814067961f28357256e8fe27544f4
Installing sd-webui-controlnet requirement: changing opencv-python version from 4.7.0.72 to 4.8.0
Checking roop requirements
Install insightface==0.7.3
Installing sd-webui-roop requirement: insightface==0.7.3
Install onnx==1.14.0
Installing sd-webui-roop requirement: onnx==1.14.0
Install onnxruntime==1.15.0
Installing sd-webui-roop requirement: onnxruntime==1.15.0
Install opencv-python==4.7.0.72
Installing sd-webui-roop requirement: opencv-python==4.7.0.72
Launching Web UI with arguments: --xformers --medvram-sdxl --no-half-vae --no-gradio-queue --theme dark --autolaunch
[-] ADetailer initialized. version: 23.9.2, num models: 9
2023-09-12 21:11:41,712 - ControlNet - INFO - ControlNet v1.1.410
ControlNet preprocessor location: C:\Users\Winnertmp\a1111\stable-diffusion-webui\extensions\sd-webui-controlnet\annotator\downloads
2023-09-12 21:11:41,896 - ControlNet - INFO - ControlNet v1.1.410
2023-09-12 21:11:42,607 - roop - INFO - roop v0.0.2
2023-09-12 21:11:42,730 - roop - INFO - roop v0.0.2
Loading weights [700528894b] from C:\Users\Winnertmp\a1111\stable-diffusion-webui\models\Stable-diffusion\juggernautXL_version2.safetensors
Creating model from config: C:\Users\Winnertmp\a1111\stable-diffusion-webui\repositories\generative-models\configs\inference\sd_xl_base.yaml
Running on local URL:  http://127.0.0.1:7860
_______________________________________________________________________________________________
Controlnet requires opencv-python version 4.8.0
sd-webui-roop requires opencv-python version 4.7.0.72
So during start both versions are loaded one by one and the start up time too much.
What should I do Please guide.

**Comment by Gourieff** [comment]
You can manually change `opencv-python==4.7.0.72` to `opencv-python` in requirements.txt
Or you can also use my fork, this moment is solved there as many other things are improved

**Comment by tmprabubiz** [comment]
There is no such line opencv-python==4.7.0.72 in requirements.txt in webui 1.6
There is another file requirements_versions.txt. Even that don't have the line opencv-python==4.7.0.72
Still I added the line opencv-python in both the files but the problem still persists
Your fork has nothing to do with this issue
Please help

**Comment by Gourieff** [comment]
[requirements.txt](https://github.com/s0md3v/sd-webui-roop/blob/main/requirements.txt) inside the "sd-webui-roop" folder

> Your fork has nothing to do with this issue

Of course, no - because this issue is solved there
